### ISSUE TITLE
Remove "react" from the name and README

### ISSUE THREAD

**Issue by ejfrancis** [kennethjiang/js-file-download#19]
This package works great, but it doesn't really have anything to do with React. It just exports a function that you can use to download an object as a file to the browser. I suggest renaming it as just "file-download" or something similar, and removing references to "React" in the documentation, so that others who aren't using React don't get the impression that they can't use it.

**Comment by kennethjiang** [comment]
Good point! Will get to it at some point. Feel free to send a PR to remove all references to React. Thanks!

**Comment by kennethjiang** [comment]
This should be closed by PR #25
