### ISSUE TITLE
Unable to open a downloaded epub file

### ISSUE THREAD

**Issue by athiramukundan** [kennethjiang/js-file-download#22]
This is in reference to [this stackoverflow question](https://stackoverflow.com/questions/45760274/download-a-epub-file-through-axios-react-file-download-lbraries-in-reactjs)

I am trying to download an epub file and I see the file being downloaded. But I am unable to open the file. I think it is corrupted or not saved to disk properly.

Here is my code - 
`const FileDownload = require('react-file-download');`
`export const handleDownload = (url, bookName) => {`
  `axios.get(url).then((res) => { FileDownload(res.data, bookName+'.epub', 
  "application/epub+zip");});} `

I also tried ` FileDownload(res.data, bookName+'.epub', "application/zip")` 

Any help is appreciated. Thanks.

**Comment by kennethjiang** [comment]
This sounds like an interesting problem. Unfortunately I'm super busy recently. You are more than welcome to take a stab at this issue. Otherwise I will circle back to it when I am more available. But that could be weeks or months later.

**Comment by CalgaryMichael** [comment]
This is an old issue and I imagine the OP has resolved the problem, but I will leave this comment for posterity.

The issue may be that you are not setting the `responseType` on the API call. I believe the following would fix the issue:

```javascript
axios.get(url, { responseType: 'arraybuffer' }).then((res) => { FileDownload(res.data, bookName+'.epub', "application/epub+zip");});}
```

*Note*: I have never used `axios`, but this is what I believe the equivalent would be for bare `XMLHttpRequest`

**Comment by agmcleod** [comment]
@CalgaryMichael thanks for that. Fixed an issue I had with downloading a zip file.
