### ISSUE TITLE
Does not work with iphone devices

### ISSUE THREAD

**Issue by vivek12345** [kennethjiang/js-file-download#29]
Since ios7 devices require a hard touch to either download or open in new tab, this code ain't working for iPhone devices.
Click does  not open the blob url file in a new tab.

**Comment by ThekhoN** [comment]
Any one got a fix for this?

**Comment by jiteshkriplani** [comment]
I am also facing the same issue. Any solution??

**Comment by VivekNayyar** [comment]
I got a temporary fix by using filesaver.js

**Comment by vivek12345** [comment]
I got a temporary fix for this using filesaver.js
https://github.com/eligrey/FileSaver.js/

Also another thing to keep in mind here working with ios devices is that do not put a tool tip on your anchor buttons because for ios devices you will then need to do a double click in order to open it in new tab. 

Regarding the download thing, you can not programmatically download on ios devices, you will have to open it in a new tab. That's how it works on ios

**Comment by robmarshall** [comment]
Solution to this is updating this line: https://github.com/kennethjiang/js-file-download/blob/1e7eb4d86cc660751660c81a55b9e50b0dadff2a/file-download.js#L33

to: 200

**Comment by robmarshall** [comment]
@kennethjiang If I create a PR for this, would you be happy to merge it? I need it for a project I am working on.

**Comment by kennethjiang** [comment]
merged and released in 0.4.12. Closing now. Thanks everyone for pitching in!
