### ISSUE TITLE
download the image bug not open

### ISSUE THREAD

**Issue by biology-w** [kennethjiang/js-file-download#30]
import fileDownload from 'js-file-download'
fileDownload('https://goss.vcg.com/fabb02f0-3c8f-11e8-84d4-a5652b728265.jpg', 'test.jpg')

download the iamge bug not open

**Comment by biology-w** [comment]
Do not open the test. jpg image.

**Comment by evliu** [comment]
you need to pass in the data, not a URL

**Comment by kennethjiang** [comment]
Thanks @evliu for helping me provide the answer!

**Comment by sajidunnar** [comment]
@evliu  Can you plesae share example to get link as data  ?
