### ISSUE TITLE
Step by Step guide to migrate from react-file-download@0.3.5 to js-file-download

### ISSUE THREAD

**Issue by saostad** [kennethjiang/js-file-download#31]
today after 
`npm` i
I got this message:

> npm WARN deprecated react-file-download@0.3.5: WARNING: This project has been renamed to js-file-download. Use js-file-download instead.

but in change-log or documents I couldn't find any migration guide. 
can anybody provide a step by step guide please?

**Comment by RickMeijer** [comment]
Have you tried renaming import path from 'react-file-download' to 'js-file-download'?

**Comment by saostad** [comment]
thanks, it works.

**Comment by kennethjiang** [comment]
Awesome. Thx @RickMeijer for helping me respond!
