### ISSUE TITLE
Using this package with Reactjs

### ISSUE THREAD

**Issue by emanuel281** [kennethjiang/js-file-download#33]
I tried using this package with Reactjs and it doesn't seem to work.
It seems to just save an empty PDF without actually querying the API.

**Comment by amacar** [comment]
I believe that you are using it wrong. It works perfectly with reactjs. Show your example.

**Comment by kennethjiang** [comment]
Thanks @amacar for helping me provide an answer!

**Comment by IgorBelyayev** [comment]
I've ran into this exact issue too. Downloading a PDF in React results in a blank PDF.

**Comment by IgorBelyayev** [comment]
I am using `axios` and I had to add `responseType: 'blob'` to the `axios` config to get the resulting PDF to not be blank.
