### ISSUE TITLE
js-file-download does not downloads png/jpg files.

### ISSUE THREAD

**Issue by afrazahmad21** [kennethjiang/js-file-download#36]
Hi,
I am currently working in a react project. I want to download file via url (http://developers.iqvis.com:8082/5b339dae14dd2757b711e56f/1530185975056-iqvis.png) but downloading png file and opening it gives error (Fatal error reading a png file: Not a png file)

here is sample code

```
  axios.get(apiUrl)
      .then((response) => {
        fileDownlaod(response.data, fileName);
      })
      .catch((err) => {
        console.log(err);
      });
```

**Comment by neomorphic** [comment]
Try adding the following option to your get request : 
```javascript
{ responseType: 'arraybuffer' }
```
eg:

 ```javascript
axios.get(apiUrl, { responseType: 'arraybuffer' } )
  .then((response) => {
    fileDownlaod(response.data, fileName);
  })
  .catch((err) => {
    console.log(err);
  });
```
That worked for me.

**Comment by vilbergs** [comment]
Should this issue be closed?
