### ISSUE TITLE
Updated type definitions don't appear to have been published

### ISSUE THREAD

**Issue by danielearwicker** [kennethjiang/js-file-download#46]
The type definitions in this repo support Blob parameter as well as string. But the latest published version does not include this change.

**Comment by kennethjiang** [comment]
The type definition was added by @Domino987 as a PR. I'm not familiar with how it works. If you can submit a PR for this i'll be happy to merge it.

**Comment by hassankhan** [comment]
@kennethjiang if you publish a new version of the package on NPM, the types will also be updated 😉

**Comment by kennethjiang** [comment]
Just published a new version. Can you check if the type definition is available now? @hassankhan 

Bear with me for all these basic mistakes and questions since I have not caught up on type definition in JS.

**Comment by hassankhan** [comment]
Had a quick look and it all looks good to me 👍

**Comment by kennethjiang** [comment]
Awesome. Closing this issue.
