### ISSUE TITLE
get a broken file

### ISSUE THREAD

**Issue by ghost** [kennethjiang/js-file-download#54]
"js-file-download": "^0.4.8",

`
import download from "js-file-download";

 download('http://lixing-develop.oss-cn-hangzhou.aliyuncs.com/large_file/1573546365135.png','你')
`
where fix it??

**Comment by jhoanborges** [comment]
same problem

**Comment by zhangminggeek** [comment]
same problem in 0.4.12

**Comment by zhangminggeek** [comment]
it works

```javascript
import Axios from axios;

function download(url: string, filename: string) {
  Axios.get(url, {
    responseType: 'blob',
  }).then(res => {
    fileDownload(res.data, filename);
  });
}
```

**Comment by ignatvilesov** [comment]
@zhangminggeek is 100% correct. Binary files should be in [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) format :rocket:

**Comment by LoveMeWithoutAll** [comment]
@zhangminggeek responseType 'blob' works perfectly. You saved my life!

**Comment by donovanclarke** [comment]
This also just saved my life. Thank you kindly.

**Comment by motevets** [comment]
Thank you @zhangminggeek for the code snippet and @ignatvilesov for the explaination.
