### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by EnderAdel** [kennethjiang/js-file-download#61]
I keep receiving the error message, that comes from the file "file-download.js" at line 3, whenever I try to run that line of code:
```
var arg = {
  data: "",
  fileName: "hey",
  fileType: "txt"
};
var fileDownload = require('js-file-download');
fileDownload(arg.data, arg.fileName + "." + arg.fileType);
```

**Comment by zzynx** [comment]
I ran that code without any errors on Windows 10 in the latest Chrome and it created an empty hey.txt file.
What's your browser type and version? OS? (Latest js-file-download version, I presume.)

**Comment by EnderAdel** [comment]
I use the latest versions of Electron, chrome, and js-file-downlaod.

**Comment by adesm** [comment]
alloo still got message Blob is not defined. why ? please?

**Comment by EnderAdel** [comment]
I've also been getting that Blob message and I didn't know why. So I've removed the package and used another tactic to download things...

**Comment by gnorbsl** [comment]
Same issue
