### ISSUE TITLE
Trying to download PDF file but Failed to load PDF

### ISSUE THREAD

**Issue by theromie** [kennethjiang/js-file-download#69]
I try to download the file in react using Axios but it failing in both conditions.

> add `{ responseType: 'blob' }` to Axios and added `fileDownload(res.data, fileName);` but it gives **Failed to load PDF document.**

> Removed `{ responseType: 'blob' }` to Axios and added `fileDownload(res.data.body, fileName);` but its gives blank file with no content.
I am using Nodejs as backend with sending response in `fs.createReadStream() `and `pipe()`

**Comment by kindrowboat** [comment]
Hey @theromie. Could you post a small repo that reproduces the problem?

**Comment by theromie** [comment]
@motevets I solve this issue. It was some error in the backend.
